[versions]
asciidoctor = "4.0.5"
cucumber = "7.31.0"
cucumber-companion = "1.3.0"
mockito-kotlin = "6.2.2"
rest-assured = "6.0.0"
spotless = "8.2.0"
spring-boot = "4.0.2"
spring-cloud-contract = "5.0.2"
spring-cloud = "2025.1.0"
spring-dependency-management = "1.1.7"

[libraries]
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor" }
cucumber-companion = { id = "com.gradle.cucumber.companion", version.ref = "cucumber-companion" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-cloud-contract = { id = "org.springframework.cloud.contract", version.ref = "spring-cloud-contract" }